### ISSUE TITLE
No connection options were found in any orm configuration files

### ISSUE THREAD

**Issue by Barno** [Tony133/nestjs-api-boilerplate-jwt#144]
Hello, I get this error 
`No connection options were found in any orm configuration files`

after run
`ts-node node_modules/.bin/typeorm migration:run`

nest -v
8.1.5

node -v
v17.5.0

ts-node -v
v10.5.0

**Comment by Tony133** [comment]
Hi @Barno, sorry for the late reply, have you tried using the `ormconfig.json` file?
such as this:

```
{
   "type": "mysql",
   "host": "localhost",
   "port": 3306,
   "username": "my_username",
   "password": "my_password",
   "database": "my_database",
   "synchronize": true,
   "logging": false,
   "entities": [
      "dist/**/*.entity.js"
   ],
   "migrations": [
      "dist/migrations/**/*.js"
   ],
   "subscribers": [
      "dist/subscriber/**/*.js"
   ],
   "cli": {
      "migrationsDir": "src/migrations",
      "subscribersDir": "src/subscriber"
   }
}
```

**Comment by Tony133** [comment]
I confirm that it works with the `ormconfig.json`

**Comment by Tony133** [comment]
Ok so as not to make things a bit complex during the migrations I put back the file `ormconfig.json`, I have updated the readme.
