### ISSUE TITLE
Token auth flow. Refresh token ideas?

### ISSUE THREAD

**Issue by dailydismay** [Tony133/nestjs-api-boilerplate-jwt#455]

**Comment by Tony133** [comment]
Hi @dailydismay,

Sorry for the late reply, it's been a busy few weeks, however I will also be adding the refresh token feature soon.

**Comment by dailydismay** [comment]
@Tony133 

What about storing refresh token binded to concrete device. Any ideas on unique identifiers for devices?

**Comment by dailydismay** [comment]
I can contribute if u want

**Comment by Tony133** [comment]
Hi @dailydismay, sorry for the late reply, 🙏🏻

I created a branch to add the update token, I would also like to add the control to invalidate the token, although there are many ways to do it, I am considering to do it via redis, however if you need the update token part, use this branch `feat/add-refresh-token` after cloning the repository. 

As far as unique device identifiers, at the moment I have not yet had the opportunity to do this, in the projects I've been a part of, the authentication part was only required a jwt token without an update token or a basic auth token.

I have created this boilerplate for the NestJS community, hoping it will be useful to those who use NestJS, so the developer has a base from which to meet their needs.

I hope I have been of help.

**Comment by Tony133** [comment]
We keep track of this here: https://github.com/Tony133/nestjs-api-boilerplate-jwt/pull/532
